version: "3.4"
services:
  server:
    image: shootingtime/bossaboxapi:1.0
    container_name: bossabox-api
    volumes:
      - .:/usr/src/
    depends_on:
      - database
    ports:
      - "3000:3000"
    networks:
      - bossa-network

  database:
    image: postgres:11.2-alpine
    container_name: bossabox-database
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: bossabox
      POSTGRES_DB: vuttr
    ports:
      - "5432:5432"
    networks:
      - bossa-network

  migration:
    image: shootingtime/bossaboxapi:1.0
    command: ["npm", "run", "migrate"]
    depends_on:
      - database
    networks:
      - bossa-network

networks:
  bossa-network:
    driver: bridge
