openapi: 3.0.0
info:
  title: BossaBox Challange API
  description: This is a api for app Very Useful Tools to Remember.
  version: 0.1.0
  contact:
    name: Ruan Linos Alves
    email: ruandeveloper@hotmail.com
servers:
  - url: http://localhost:3000/
    description: Development server.

components:
  schemas:
    Tool:
      type: object
      properties:
        title:
          type: string
        link:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string

paths:
  /tools:
    get:
      summary: This route returns a list of tools.
      description: This route returns a list of all tools, containing all tool information.
      responses:
        "200":
          description: A JSON array of tools
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tool"
    post:
      summary: Route used to create a new tool in the database.
      description: Used to create a new tool, must be passed in the body title, link, description, tags.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                link:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        "201":
          description: After creating a tool, it returns an object with the tool information.
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
        "5XX":
          description: Unexpected error.

  /tools/{toolID}:
    put:
      summary: Route used to change elements of a given tool.
      parameters:
        - in: path
          name: toolID
          schema:
            type: integer
          required: true
          description: The param id is the unique identifier, which is required to modify a specific tool.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                link:
                  type: string
                tags:
                  type: array
                  items:
                    type: string

      responses:
        "204":
          description: You successfully changed the tool.
        "400":
          description: Bad request. Tool ID must be an integer and higher than 0.
        "404":
          description: Don't possibly find a tool with the informed id.
    delete:
      summary: This route is to delete a specific tool.
      parameters:
        - in: path
          name: toolID
          schema:
            type: integer
          required: true
          description: ID numeric for delete a specific tool
      responses:
        "204":
          description: You successfully deleted the tool.
        "400":
          description: Bad request. Tool ID must be an integer and higher than 0.
        "404":
          description: Don't possibly find a tool with the informed id.
